const CONFIG = {
    introTitle: 'Hiiii chào cou nho🤗🤗',
    introDesc: `Tớ có điều này muốn hỏi cou phải trả lời thật lòng nhe!!`,
    btnIntro: 'Okiiiii😊',
    title: 'Có lẽ ngay từ lần nhìn thấy nụ cười của cậu tớ đã iu cậu mất gòi 😍',
    desc: 'cậu cũng iu tớ phải hok',
    btnYes: 'Chắc là vậy á🥰',
    btnNo: 'Đéo, Nodoor',
    question: 'Trên thế giới có hơn 7 tỉ người mà tớ lại yêu cậu🥰😍',
    btnReply: 'Gửi cho Cậu<3',
    reply: 'Yêu thì yêu mà không yêu thì cũng yêu tớ cũng không biết nũa cậu cứ như trái đất ấy đầy lực hấp dẫn tớ ó😘😘😘',
    mess: 'Tớ biết mà 🥰. Yêu cậu nhiều nhiều 😘😘',
    messDesc: 'Tối mai 7h tớ qua nhà đón cậu nhé, my lover😍😍',
    btnAccept: 'Okiiiii un😘',
    messLink: 'https://gdf32547.github.io/Sucessed/',
}